---
- hosts: all
  gather_facts: yes

- hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required modules (Python3-pip-venv)
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Flask
      become: true
      pip:
        executable: pip3
        name: flask
        state: present
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Create flask-app directory in webservers
      file:
        path: /home/ubuntu/flask-app
        state: directory
    - name: Change directory to flask-app
      become: yes
      become_user: ubuntu
      shell: cd /home/ubuntu/flask-app

    - name: Install virtualenv package
      apt:
        name: python3-virtualenv
        state: present
        update_cache: yes

    - name: Creating virtual environment
      file:
        path: /home/ubuntu/flask-app/venv
        state: directory
        mode: '0755'

    - name: Set up virtual environment
      pip:
        name: Flask
        virtualenv: /home/ubuntu/flask-app/venv

    - name: Set permissions for virtual environment
      become: yes
      become_user: root
      file:
        path: /home/ubuntu/flask-app/venv
        mode: '0755'
        recurse: yes

    - name: Copy Flask app file
      copy:
        src: application2.py
        dest: /home/ubuntu/flask-app/venv/application2.py
- hosts: HAproxy
  become: yes
  tasks:
    - name: Install HAproxy
      apt:
        name: haproxy
        state: latest

    - name: Configuring HAproxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      become: yes

    - name: Restarting HAproxy
      service:
        name: haproxy
        state: restarted
